const characterData = {
    Amber: {
        name: 'Amber',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Amber.png",
        rarity: 4,
        element: "pyro",
        weapon: "Bow",
        description: 'Amber is a Pyro user who wields a bow. She is a member of the Outriders of Mondstadt and is known for her loyalty and positive attitude.',
      },
      Barbara: {
        name: 'Barbara',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Barbara.png",
        rarity: 4,
        element: "hydro",
        weapon: "Catalyst",
        description: 'Barbara is a Hydro user who wields a catalyst. She is a Deaconess of the Church of Favonius and has a gentle and caring personality.',
      },
      Beidou: {
        name: 'Beidou',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Beidou.png",
        rarity: 4,
        element: "electro",
        weapon: "Claymore",
        description: 'Beidou is an Electro user who wields a claymore. She is the captain of the Crux Fleet and is known for her strong will and leadership skills.',
      },
      Bennett: {
        name: 'Bennett',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Bennett.png",
        rarity: 4,
        element: "pyro",
        weapon: "Sword",
        description: 'Bennett is a Pyro user who wields a sword. He is a member of the Adventurers’ Guild and is known for his optimism and determination.',
      },
      Candace: {
        name: 'Candace',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Candace.png",
        rarity: 4,
        element: "hydro",
        weapon: "Polearm",
        description: 'Candace is a Hydro user who wields a polearm. She is known for her grace and intelligence, and is highly respected in her community.',
      },
      Charlotte: {
        name: 'Charlotte',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Charlotte.png",
        rarity: 4,
        element: "cryo",
        weapon: "Bow",
        description: 'Charlotte is a Cryo user who wields a bow. She is a skilled reporter with a keen eye for detail and a strong sense of justice.',
      },
      Chongyun: {
        name: 'Chongyun',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Chongyun.png",
        rarity: 4,
        element: "cryo",
        weapon: "Claymore",
        description: 'Chongyun is a Cryo user who wields a claymore. He is an exorcist with a strong sense of duty and a warm heart, dedicated to banishing evil spirits.',
      },
      Collei: {
        name: 'Collei',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Collei.png",
        rarity: 4,
        element: "dendro",
        weapon: "Bow",
        description: 'Collei is a Dendro user who wields a bow. She is a kind-hearted ranger who strives to protect her homeland and its inhabitants.',
      },
      Cyno: {
        name: 'Cyno',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Cyno.png",
        rarity: 5,
        element: "electro",
        weapon: "Polearm",
        description: 'Cyno is an Electro user who wields a polearm. He is a stern and formidable warrior, known for his strict sense of justice and discipline.',
      },
      Dainsleif: {
        name: 'Dainsleif',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Dainsleif.png",
        rarity: 5,
        element: "unknown",
        weapon: "Sword",
        description: 'Dainsleif is an enigmatic character with unknown elemental affinity. He is a mysterious figure with a deep connection to Teyvat’s history and its secrets.',
      },
      Diluc: {
        name: 'Diluc',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Diluc.png",
        rarity: 5,
        element: "pyro",
        weapon: "Claymore",
        description: 'Diluc is a Pyro user who wields a claymore. He is a wealthy and influential figure in Mondstadt, known for his dedication to protecting his city from danger.',
      },
      Diona: {
        name: 'Diona',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Diona.png",
        rarity: 4,
        element: "cryo",
        weapon: "Bow",
        description: 'Diona is a Cryo user who wields a bow. She is a bartender with a strong dislike for alcohol, and is known for her tough demeanor and caring nature.',
      },
      Eula: {
        name: 'Eula',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Eula.png",
        rarity: 5,
        element: "cryo",
        weapon: "Claymore",
        description: 'Eula is a Cryo user who wields a claymore. She is a skilled warrior and the Spindrift Knight of Mondstadt, known for her noble heritage and strong sense of justice.',
      },
      Fischl: {
        name: 'Fischl',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Fischl.png",
        rarity: 4,
        element: "electro",
        weapon: "Bow",
        description: 'Fischl is an Electro user who wields a bow. She is a self-proclaimed “Prinzessin der Verurteilung” with a deep connection to the supernatural and a flair for the dramatic.',
      },
      Ganyu: {
        name: 'Ganyu',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Ganyu.png",
        rarity: 5,
        element: "cryo",
        weapon: "Bow",
        description: 'Ganyu is a Cryo user who wields a bow. She is a half-qilin Adeptus from Liyue and serves as the general secretary of the Liyue Qixing.',
      },
      HuTao: {
        name: 'Hu Tao',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Hu_Tao.png",
        rarity: 5,
        element: "pyro",
        weapon: "Polearm",
        description: 'Hu Tao is a Pyro user who wields a polearm. She is the 77th Director of the Wangsheng Funeral Parlor and is known for her playful and enigmatic personality.',
      },
      Jean: {
        name: 'Jean',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Jean.png",
        rarity: 5,
        element: "anemo",
        weapon: "Sword",
        description: 'Jean is an Anemo user who wields a sword. She is the Acting Grand Master of the Knights of Favonius and is known for her strong sense of duty and leadership.',
      },
      Kaeya: {
        name: 'Kaeya',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Kaeya.png",
        rarity: 4,
        element: "cryo",
        weapon: "Sword",
        description: 'Kaeya is a Cryo user who wields a sword. He is the Cavalry Captain of the Knights of Favonius, known for his charming demeanor and mysterious background.',
      },
      Kazuha: {
        name: 'Kazuha',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Kazuha.png",
        rarity: 5,
        element: "anemo",
        weapon: "Sword",
        description: 'Kazuha is an Anemo user who wields a sword. He is a wandering samurai from Inazuma, known for his poetic nature and calm demeanor.',
      },
      Keqing: {
        name: 'Keqing',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Keqing.png",
        rarity: 5,
        element: "electro",
        weapon: "Sword",
        description: 'Keqing is an Electro user who wields a sword. She is the Yuheng of the Liyue Qixing and is known for her pragmatic and diligent approach to her duties.',
      },
      Albedo: {
        name: 'Albedo',
        imgSrc: "https://rerollcdn.com/GENSHIN/Characters/1/Albedo.png",
        rarity: 5,
        element: "geo",
        weapon: "Sword",
        description: 'Albedo is a Geo user who wields a sword. He is the Chief Alchemist of the Knights of Favonius and the leader of the Alchemist Guild.',
      }
  };
  
  export default characterData